use bevy::prelude::*;
use std::collections::{HashMap, HashSet};
use std::iter;

use crate::{
    civilians::types::ProspectingKnowledge,
    economy::{
        nation::Capital,
        transport::{Depot, Port},
    },
    map::tile_pos::{HexExt, TilePosExt},
    resources::{ResourceType, TileResource},
};
use bevy_ecs_tilemap::prelude::{TilePos, TileStorage};

use crate::economy::workforce::Workforce;
use crate::economy::stockpile::Stockpile;
use crate::economy::buildings::*;

/// Resource that stores the total connected production output for each nation.
#[derive(Resource, Default, Debug)]
pub struct ConnectedProduction {
    /// Aggregated totals per nation and resource type.
    /// `(u32, u32)` is `(number_of_improvements, total_output)`.
    pub totals: HashMap<Entity, HashMap<ResourceType, (u32, u32)>>,
    /// Individual tile contributions captured for debugging/visualization.
    pub tiles: Vec<ConnectedTileOutput>,
}

/// Details about one tile contributing to connected production.
#[derive(Debug, Clone)]
pub struct ConnectedTileOutput {
    pub owner: Entity,
    pub resource_type: ResourceType,
    pub tile_pos: TilePos,
    pub output: u32,
    pub source: ConnectedTileSource,
}

/// Origin of a connected production contribution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ConnectedTileSource {
    /// Output generated by an improvement linked through the network.
    Improvement,
    /// Fish produced directly by a connected port.
    Port,
    /// Baseline yield from tiles adjacent to a nation's capital.
    Baseline,
}

impl ConnectedTileSource {
    pub fn marker(self) -> &'static str {
        match self {
            ConnectedTileSource::Improvement => "I",
            ConnectedTileSource::Port => "P",
            ConnectedTileSource::Baseline => "B",
        }
    }
}

/// Calculates the total production from all resource tiles connected to the rail network.
/// Observer triggered by RecomputeConnectivity events (runs after compute_rail_connectivity).
pub fn calculate_connected_production(
    _trigger: On<crate::economy::transport::RecomputeConnectivity>,
    mut production: ResMut<ConnectedProduction>,
    connected_depots: Query<&Depot>,
    connected_ports: Query<&Port>,
    capitals: Query<(Entity, &Capital)>,
    tile_storage: Query<&TileStorage>,
    tile_resources: Query<&TileResource>,
    prospecting_knowledge: Res<ProspectingKnowledge>,
) {
    // Clear previous data
    production.totals.clear();
    production.tiles.clear();

    let mut processed_tiles: HashSet<TilePos> = HashSet::new();

    let Ok(tile_storage) = tile_storage.single() else {
        return;
    };

    fn record_output(
        production: &mut ConnectedProduction,
        processed_tiles: &mut HashSet<TilePos>,
        owner: Entity,
        resource_type: ResourceType,
        tile_pos: Option<TilePos>,
        output: u32,
        count_improvement: bool,
        source: ConnectedTileSource,
    ) {
        if output == 0 {
            return;
        }

        let nation_production = production.totals.entry(owner).or_default();
        let entry = nation_production.entry(resource_type).or_default();
        if count_improvement {
            entry.0 += 1;
        }
        entry.1 += output;

        if let Some(pos) = tile_pos {
            let first_entry = processed_tiles.insert(pos);

            if first_entry {
                production.tiles.push(ConnectedTileOutput {
                    owner,
                    resource_type,
                    tile_pos: pos,
                    output,
                    source,
                });
            }
        }
    }

    fn process_improvement(
        production: &mut ConnectedProduction,
        processed_tiles: &mut HashSet<TilePos>,
        owner: Entity,
        position: TilePos,
        tile_storage: &TileStorage,
        tile_resources: &Query<&TileResource>,
        prospecting_knowledge: &ProspectingKnowledge,
    ) {
        let center_hex = position.to_hex();
        let neighbors = center_hex.all_neighbors();
        let tiles_to_check = neighbors.iter().copied().chain(iter::once(center_hex));

        for hex in tiles_to_check {
            if let Some(tile_pos) = hex.to_tile_pos() {
                if processed_tiles.contains(&tile_pos) {
                    continue; // Avoid double-counting
                }
                if let Some(tile_entity) = tile_storage.get(&tile_pos)
                    && let Ok(resource) = tile_resources.get(tile_entity)
                    && resource.discovered
                    && resource.get_output() > 0
                {
                    if resource.requires_prospecting()
                        && !prospecting_knowledge.is_discovered_by(tile_entity, owner)
                    {
                        continue;
                    }
                    record_output(
                        production,
                        processed_tiles,
                        owner,
                        resource.resource_type,
                        Some(tile_pos),
                        resource.get_output(),
                        true,
                        ConnectedTileSource::Improvement,
                    );
                }
            }
        }
    }

    let production = production.as_mut();

    // Process connected depots
    for depot in connected_depots.iter().filter(|d| d.connected) {
        process_improvement(
            production,
            &mut processed_tiles,
            depot.owner,
            depot.position,
            tile_storage,
            &tile_resources,
            &prospecting_knowledge,
        );
    }

    // Process connected ports
    for port in connected_ports.iter().filter(|p| p.connected) {
        process_improvement(
            production,
            &mut processed_tiles,
            port.owner,
            port.position,
            tile_storage,
            &tile_resources,
            &prospecting_knowledge,
        );
        record_output(
            production,
            &mut processed_tiles,
            port.owner,
            ResourceType::Fish,
            Some(port.position),
            2,
            true,
            ConnectedTileSource::Port,
        );
    }

    // Process capital-adjacent tiles for baseline yields
    for (owner, capital) in capitals.iter() {
        let center_hex = capital.0.to_hex();

        for hex in center_hex.all_neighbors() {
            if let Some(tile_pos) = hex.to_tile_pos() {
                if processed_tiles.contains(&tile_pos) {
                    continue;
                }
                if let Some(tile_entity) = tile_storage.get(&tile_pos)
                    && let Ok(resource) = tile_resources.get(tile_entity)
                    && resource.discovered
                {
                    if resource.requires_prospecting()
                        && !prospecting_knowledge.is_discovered_by(tile_entity, owner)
                    {
                        continue;
                    }

                    if resource.resource_type.is_baseline_yield_eligible() {
                        record_output(
                            production,
                            &mut processed_tiles,
                            owner,
                            resource.resource_type,
                            Some(tile_pos),
                            1,
                            false,
                            ConnectedTileSource::Baseline,
                        );
                    }
                }
            }
        }
    }
}

/// Collects resources from connected production and adds them to nation stockpiles.
/// Runs at the start of each turn (PlayerTurn phase) to harvest resources.
/// Resources are only collected up to the allocated transport capacity for each commodity.
pub fn collect_connected_production(
    connected: Res<ConnectedProduction>,
    transport_allocations: Res<crate::economy::transport::TransportAllocations>,
    mut nations: Query<(Entity, &mut Stockpile)>,
) {
    use crate::economy::transport::TransportCommodity;

    for (nation_entity, mut stockpile) in nations.iter_mut() {
        if let Some(nation_totals) = connected.totals.get(&nation_entity) {
            for (resource_type, (_improvement_count, total_output)) in nation_totals.iter() {
                if *total_output == 0 {
                    continue;
                }

                let good = resource_type.to_good();

                // Check if there's an allocated transport capacity for this resource
                if let Some(commodity) = TransportCommodity::from_good(good) {
                    let allocation = transport_allocations.slot(nation_entity, commodity);
                    let amount_to_collect = allocation.granted.min(*total_output);

                    if amount_to_collect > 0 {
                        stockpile.add(good, amount_to_collect);
                        info!(
                            "Nation {:?} collected {} {:?} from connected production (allocated: {}, available: {})",
                            nation_entity,
                            amount_to_collect,
                            good,
                            allocation.granted,
                            total_output
                        );
                    } else if allocation.granted == 0 {
                        info!(
                            "Nation {:?} has {} {:?} available but no transport capacity allocated",
                            nation_entity, total_output, good
                        );
                    }
                } else {
                    // This should never happen for resources - all resource types have commodity mappings
                    error!(
                        "Missing TransportCommodity mapping for good {:?} when collecting connected production for nation {:?}. This violates the transport allocation mechanic.",
                        good, nation_entity
                    );
                    panic!(
                        "Missing TransportCommodity mapping for good {:?} during connected production collection",
                        good
                    );
                }
            }
        }
    }
}

/// Runs production across all entities that have both a Stockpile and a Building.
/// Consumes reserved resources and produces outputs.
/// Production rules follow 2:1 ratios (2 inputs → 1 output).
/// Production now requires labor points from workers.
///
/// Note: This system runs via OnEnter(TurnPhase::Processing) in ProcessingSet::Production,
/// so no phase check is needed.
pub fn run_production(
    mut q: Query<(
        Option<&Workforce>,
        &mut Stockpile,
        &Building,
        &mut ProductionSettings,
    )>,
) {
    for (workforce_opt, mut stock, building, mut settings) in q.iter_mut() {
        // Calculate available labor (0 if no workforce)
        let available_labor = workforce_opt.map(|w| w.available_labor()).unwrap_or(0);

        // Each unit of production requires 1 labor point
        // This acts as another constraint on production alongside capacity and inputs
        let max_from_labor = available_labor;
        let Some(recipe) = production_recipe(building.kind) else {
            continue;
        };

        let desired_output = settings
            .target_output
            .min(max_from_labor)
            .min(building.capacity);
        if desired_output == 0 {
            settings.target_output = 0;
            continue;
        }

        // Select variant based on stockpile availability instead of stored choice
        let Some(variant) = recipe.best_variant_for_stockpile(&stock) else {
            settings.target_output = 0;
            debug!(
                "Skipping production for {:?}: no suitable variant found",
                building.kind
            );
            continue;
        };

        let output_per_batch = variant.primary_output_amount();
        if output_per_batch == 0 {
            settings.target_output = 0;
            continue;
        }

        let target_batches = desired_output.div_ceil(output_per_batch);
        if target_batches == 0 {
            settings.target_output = 0;
            continue;
        }

        let (produced_output, consumption) = execute_variant(&mut stock, variant, target_batches);

        if produced_output < desired_output {
            log_production_shortfall(
                building.kind,
                variant,
                desired_output,
                produced_output,
                &consumption,
            );
        }

        settings.target_output = produced_output;
    }
}

#[derive(Clone, Debug)]
struct ConsumptionRecord {
    ingredient: Ingredient,
    consumed: u32,
    required: u32,
}

fn execute_variant(
    stock: &mut Stockpile,
    variant: RecipeVariant,
    target_batches: u32,
) -> (u32, Vec<ConsumptionRecord>) {
    if target_batches == 0 {
        return (0, Vec::new());
    }

    let mut actual_batches = target_batches;
    let mut consumption = Vec::with_capacity(variant.inputs().len());

    for ingredient in variant.inputs() {
        let required = ingredient.amount.saturating_mul(target_batches);
        let consumed = if required > 0 {
            stock.consume_reserved(ingredient.good, required)
        } else {
            0
        };
        if ingredient.amount > 0 {
            actual_batches = actual_batches.min(consumed / ingredient.amount);
        }
        consumption.push(ConsumptionRecord {
            ingredient: *ingredient,
            consumed,
            required,
        });
    }

    let primary_output = variant.primary_output();
    let mut produced_primary = 0;

    for output in variant.outputs() {
        let produced_amount = actual_batches.saturating_mul(output.amount);
        if produced_amount > 0 {
            stock.add(output.good, produced_amount);
        }
        if primary_output.is_some_and(|primary| primary.good == output.good) {
            produced_primary = produced_amount;
        }
    }

    (produced_primary, consumption)
}

fn log_production_shortfall(
    building_kind: BuildingKind,
    variant: RecipeVariant,
    requested_output: u32,
    produced_output: u32,
    consumption: &[ConsumptionRecord],
) {
    if produced_output >= requested_output {
        return;
    }

    let Some(output_good) = variant.primary_output_good() else {
        warn!(
            "{:?}: requested {} output but recipe variant has no primary output good (produced {}). Consumption: {:?}",
            building_kind, requested_output, produced_output, consumption
        );
        return;
    };

    let details = if consumption.is_empty() {
        "no inputs consumed".to_string()
    } else {
        consumption
            .iter()
            .map(|record| {
                format!(
                    "{:?} {}/{}",
                    record.ingredient.good, record.consumed, record.required
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    info!(
        "{:?}: requested {} {:?} but produced {} ({})",
        building_kind, requested_output, output_good, produced_output, details
    );
}

#[cfg(test)]
mod tests {
    use crate::economy::production::{ConnectedTileSource, calculate_connected_production};
    use crate::economy::transport::RecomputeConnectivity;
    use crate::economy::*;
    use crate::{
        civilians::types::ProspectingKnowledge,
        economy::{nation::Capital, transport::Port},
        map::tiles::TerrainType,
        resources::{ResourceType, TileResource},
        test_utils::{create_test_tile, create_test_tilemap},
    };
    use bevy_ecs_tilemap::prelude::TilePos;

    #[test]
    fn capital_adjacent_tiles_provide_baseline_yield() {
        let mut app = App::new();
        app.insert_resource(ConnectedProduction::default());
        app.insert_resource(ProspectingKnowledge::default());
        app.add_observer(calculate_connected_production);

        let (tilemap_entity, mut tile_storage) = create_test_tilemap(app.world_mut(), 3, 3);
        let capital_pos = TilePos { x: 1, y: 1 };
        let field_pos = TilePos { x: 1, y: 2 };

        let field_entity = create_test_tile(
            app.world_mut(),
            field_pos,
            TerrainType::Farmland,
            tilemap_entity,
            &mut tile_storage,
        );
        app.world_mut()
            .entity_mut(field_entity)
            .insert(TileResource::visible(ResourceType::Grain));

        app.world_mut()
            .entity_mut(tilemap_entity)
            .insert(tile_storage);

        let nation = app.world_mut().spawn(Capital(capital_pos)).id();

        // Trigger the observer
        app.world_mut().trigger(RecomputeConnectivity);

        let production = app.world().resource::<ConnectedProduction>();
        let nation_output = production
            .totals
            .get(&nation)
            .expect("capital-adjacent production recorded");
        let grain_entry = nation_output
            .get(&ResourceType::Grain)
            .expect("grain entry exists");
        assert_eq!(grain_entry.0, 0, "no improvements should be counted");
        assert_eq!(grain_entry.1, 1, "capital adjacency yields one grain");

        assert!(
            production.tiles.iter().any(|tile| {
                tile.owner == nation
                    && tile.resource_type == ResourceType::Grain
                    && tile.tile_pos == field_pos
                    && tile.output == 1
                    && tile.source == ConnectedTileSource::Baseline
            }),
            "baseline tile contribution recorded"
        );
    }

    #[test]
    fn connected_port_produces_two_fish() {
        let mut app = App::new();
        app.insert_resource(ConnectedProduction::default());
        app.insert_resource(ProspectingKnowledge::default());
        app.add_observer(calculate_connected_production);

        let (tilemap_entity, tile_storage) = create_test_tilemap(app.world_mut(), 3, 3);
        app.world_mut()
            .entity_mut(tilemap_entity)
            .insert(tile_storage.clone());

        let nation = app.world_mut().spawn_empty().id();
        app.world_mut().spawn(Port {
            position: TilePos { x: 1, y: 1 },
            owner: nation,
            connected: true,
            is_river: false,
        });

        // Trigger the observer
        app.world_mut().trigger(RecomputeConnectivity);

        let production = app.world().resource::<ConnectedProduction>();
        let nation_output = production
            .totals
            .get(&nation)
            .expect("port production recorded");
        let fish_entry = nation_output
            .get(&ResourceType::Fish)
            .expect("fish entry exists");
        assert_eq!(fish_entry.0, 1, "port counts as improvement for fish");
        assert_eq!(fish_entry.1, 2, "ports yield two fish");

        assert!(
            production.tiles.iter().any(|tile| {
                tile.owner == nation
                    && tile.resource_type == ResourceType::Fish
                    && tile.tile_pos == TilePos { x: 1, y: 1 }
                    && tile.output == 2
                    && tile.source == ConnectedTileSource::Port
            }),
            "port fish debug tile recorded"
        );
    }
}
