use bevy::ecs::message::MessageReader;
use bevy::prelude::*;
use std::collections::{HashMap, HashSet};
use std::iter;

use crate::{
    civilians::types::ProspectingKnowledge,
    economy::{
        nation::Capital,
        transport::{Depot, Port},
    },
    map::tile_pos::{HexExt, TilePosExt},
    resources::{ResourceType, TileResource},
};
use bevy_ecs_tilemap::prelude::{TilePos, TileStorage};

use crate::economy::workforce::Workforce;
use crate::economy::{goods::Good, stockpile::Stockpile};

/// Resource that stores the total connected production output for each nation.
#[derive(Resource, Default, Debug)]
pub struct ConnectedProduction {
    /// Aggregated totals per nation and resource type.
    /// `(u32, u32)` is `(number_of_improvements, total_output)`.
    pub totals: HashMap<Entity, HashMap<ResourceType, (u32, u32)>>,
    /// Individual tile contributions captured for debugging/visualization.
    pub tiles: Vec<ConnectedTileOutput>,
}

/// Details about one tile contributing to connected production.
#[derive(Debug, Clone)]
pub struct ConnectedTileOutput {
    pub owner: Entity,
    pub resource_type: ResourceType,
    pub tile_pos: TilePos,
    pub output: u32,
    pub source: ConnectedTileSource,
}

/// Origin of a connected production contribution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ConnectedTileSource {
    /// Output generated by an improvement linked through the network.
    Improvement,
    /// Fish produced directly by a connected port.
    Port,
    /// Baseline yield from tiles adjacent to a nation's capital.
    Baseline,
}

impl ConnectedTileSource {
    pub fn marker(self) -> &'static str {
        match self {
            ConnectedTileSource::Improvement => "I",
            ConnectedTileSource::Port => "P",
            ConnectedTileSource::Baseline => "B",
        }
    }
}

/// Calculates the total production from all resource tiles connected to the rail network.
/// This system runs after `compute_rail_connectivity` and only when connectivity changes.
pub fn calculate_connected_production(
    connectivity_events: Option<MessageReader<crate::economy::transport::RecomputeConnectivity>>,
    mut production: ResMut<ConnectedProduction>,
    connected_depots: Query<&Depot>,
    connected_ports: Query<&Port>,
    capitals: Query<(Entity, &Capital)>,
    tile_storage: Query<&TileStorage>,
    tile_resources: Query<&TileResource>,
    prospecting_knowledge: Res<ProspectingKnowledge>,
) {
    // Only recompute when connectivity changed (or always in tests where message isn't registered)
    if let Some(events) = connectivity_events
        && events.is_empty()
    {
        return;
    }
    // Note: we don't consume the events here because compute_rail_connectivity already did

    // Clear previous data
    production.totals.clear();
    production.tiles.clear();

    let mut processed_tiles: HashSet<TilePos> = HashSet::new();

    let Ok(tile_storage) = tile_storage.single() else {
        return;
    };

    fn record_output(
        production: &mut ConnectedProduction,
        processed_tiles: &mut HashSet<TilePos>,
        owner: Entity,
        resource_type: ResourceType,
        tile_pos: Option<TilePos>,
        output: u32,
        count_improvement: bool,
        source: ConnectedTileSource,
    ) {
        if output == 0 {
            return;
        }

        let nation_production = production.totals.entry(owner).or_default();
        let entry = nation_production.entry(resource_type).or_default();
        if count_improvement {
            entry.0 += 1;
        }
        entry.1 += output;

        if let Some(pos) = tile_pos {
            let first_entry = processed_tiles.insert(pos);

            if first_entry {
                production.tiles.push(ConnectedTileOutput {
                    owner,
                    resource_type,
                    tile_pos: pos,
                    output,
                    source,
                });
            }
        }
    }

    fn process_improvement(
        production: &mut ConnectedProduction,
        processed_tiles: &mut HashSet<TilePos>,
        owner: Entity,
        position: TilePos,
        tile_storage: &TileStorage,
        tile_resources: &Query<&TileResource>,
        prospecting_knowledge: &ProspectingKnowledge,
    ) {
        let center_hex = position.to_hex();
        let neighbors = center_hex.all_neighbors();
        let tiles_to_check = neighbors.iter().copied().chain(iter::once(center_hex));

        for hex in tiles_to_check {
            if let Some(tile_pos) = hex.to_tile_pos() {
                if processed_tiles.contains(&tile_pos) {
                    continue; // Avoid double-counting
                }
                if let Some(tile_entity) = tile_storage.get(&tile_pos)
                    && let Ok(resource) = tile_resources.get(tile_entity)
                    && resource.discovered
                    && resource.get_output() > 0
                {
                    if resource.requires_prospecting()
                        && !prospecting_knowledge.is_discovered_by(tile_entity, owner)
                    {
                        continue;
                    }
                    record_output(
                        production,
                        processed_tiles,
                        owner,
                        resource.resource_type,
                        Some(tile_pos),
                        resource.get_output(),
                        true,
                        ConnectedTileSource::Improvement,
                    );
                }
            }
        }
    }

    let production = production.as_mut();

    // Process connected depots
    for depot in connected_depots.iter().filter(|d| d.connected) {
        process_improvement(
            production,
            &mut processed_tiles,
            depot.owner,
            depot.position,
            tile_storage,
            &tile_resources,
            &prospecting_knowledge,
        );
    }

    // Process connected ports
    for port in connected_ports.iter().filter(|p| p.connected) {
        process_improvement(
            production,
            &mut processed_tiles,
            port.owner,
            port.position,
            tile_storage,
            &tile_resources,
            &prospecting_knowledge,
        );
        record_output(
            production,
            &mut processed_tiles,
            port.owner,
            ResourceType::Fish,
            Some(port.position),
            2,
            true,
            ConnectedTileSource::Port,
        );
    }

    // Process capital-adjacent tiles for baseline yields
    for (owner, capital) in capitals.iter() {
        let center_hex = capital.0.to_hex();

        for hex in center_hex.all_neighbors() {
            if let Some(tile_pos) = hex.to_tile_pos() {
                if processed_tiles.contains(&tile_pos) {
                    continue;
                }
                if let Some(tile_entity) = tile_storage.get(&tile_pos)
                    && let Ok(resource) = tile_resources.get(tile_entity)
                    && resource.discovered
                {
                    if resource.requires_prospecting()
                        && !prospecting_knowledge.is_discovered_by(tile_entity, owner)
                    {
                        continue;
                    }

                    if resource.resource_type.is_baseline_yield_eligible() {
                        record_output(
                            production,
                            &mut processed_tiles,
                            owner,
                            resource.resource_type,
                            Some(tile_pos),
                            1,
                            false,
                            ConnectedTileSource::Baseline,
                        );
                    }
                }
            }
        }
    }
}

/// Collects resources from connected production and adds them to nation stockpiles.
/// Runs at the start of each turn (PlayerTurn phase) to harvest resources.
/// Resources are only collected up to the allocated transport capacity for each commodity.
pub fn collect_connected_production(
    connected: Res<ConnectedProduction>,
    transport_allocations: Res<crate::economy::transport::TransportAllocations>,
    mut nations: Query<(Entity, &mut Stockpile)>,
) {
    use crate::economy::transport::TransportCommodity;

    for (nation_entity, mut stockpile) in nations.iter_mut() {
        if let Some(nation_totals) = connected.totals.get(&nation_entity) {
            for (resource_type, (_improvement_count, total_output)) in nation_totals.iter() {
                if *total_output == 0 {
                    continue;
                }

                let good = resource_type.to_good();
                
                // Check if there's an allocated transport capacity for this resource
                if let Some(commodity) = TransportCommodity::from_good(good) {
                    let allocation = transport_allocations.slot(nation_entity, commodity);
                    let amount_to_collect = allocation.granted.min(*total_output);
                    
                    if amount_to_collect > 0 {
                        stockpile.add(good, amount_to_collect);
                        info!(
                            "Nation {:?} collected {} {:?} from connected production (allocated: {}, available: {})",
                            nation_entity, amount_to_collect, good, allocation.granted, total_output
                        );
                    } else if allocation.granted == 0 {
                        info!(
                            "Nation {:?} has {} {:?} available but no transport capacity allocated",
                            nation_entity, total_output, good
                        );
                    }
                } else {
                    // This should never happen for resources - all resource types have commodity mappings
                    error!(
                        "Missing TransportCommodity mapping for good {:?} when collecting connected production for nation {:?}. This violates the transport allocation mechanic.",
                        good, nation_entity
                    );
                    panic!(
                        "Missing TransportCommodity mapping for good {:?} during connected production collection",
                        good
                    );
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::economy::production::{ConnectedTileSource, calculate_connected_production};
    use crate::economy::*;
    use crate::{
        civilians::types::ProspectingKnowledge,
        economy::{nation::Capital, transport::Port},
        map::tiles::TerrainType,
        resources::{ResourceType, TileResource},
        test_utils::{create_test_tile, create_test_tilemap},
    };
    use bevy_ecs_tilemap::prelude::TilePos;

    #[test]
    fn capital_adjacent_tiles_provide_baseline_yield() {
        let mut app = App::new();
        app.insert_resource(ConnectedProduction::default());
        app.insert_resource(ProspectingKnowledge::default());

        let (tilemap_entity, mut tile_storage) = create_test_tilemap(app.world_mut(), 3, 3);
        let capital_pos = TilePos { x: 1, y: 1 };
        let field_pos = TilePos { x: 1, y: 2 };

        let field_entity = create_test_tile(
            app.world_mut(),
            field_pos,
            TerrainType::Farmland,
            tilemap_entity,
            &mut tile_storage,
        );
        app.world_mut()
            .entity_mut(field_entity)
            .insert(TileResource::visible(ResourceType::Grain));

        app.world_mut()
            .entity_mut(tilemap_entity)
            .insert(tile_storage);

        let nation = app.world_mut().spawn(Capital(capital_pos)).id();

        app.add_systems(Update, calculate_connected_production);
        app.update();

        let production = app.world().resource::<ConnectedProduction>();
        let nation_output = production
            .totals
            .get(&nation)
            .expect("capital-adjacent production recorded");
        let grain_entry = nation_output
            .get(&ResourceType::Grain)
            .expect("grain entry exists");
        assert_eq!(grain_entry.0, 0, "no improvements should be counted");
        assert_eq!(grain_entry.1, 1, "capital adjacency yields one grain");

        assert!(
            production.tiles.iter().any(|tile| {
                tile.owner == nation
                    && tile.resource_type == ResourceType::Grain
                    && tile.tile_pos == field_pos
                    && tile.output == 1
                    && tile.source == ConnectedTileSource::Baseline
            }),
            "baseline tile contribution recorded"
        );
    }

    #[test]
    fn connected_port_produces_two_fish() {
        let mut app = App::new();
        app.insert_resource(ConnectedProduction::default());
        app.insert_resource(ProspectingKnowledge::default());

        let (tilemap_entity, tile_storage) = create_test_tilemap(app.world_mut(), 3, 3);
        app.world_mut()
            .entity_mut(tilemap_entity)
            .insert(tile_storage.clone());

        let nation = app.world_mut().spawn_empty().id();
        app.world_mut().spawn(Port {
            position: TilePos { x: 1, y: 1 },
            owner: nation,
            connected: true,
            is_river: false,
        });

        app.add_systems(Update, calculate_connected_production);
        app.update();

        let production = app.world().resource::<ConnectedProduction>();
        let nation_output = production
            .totals
            .get(&nation)
            .expect("port production recorded");
        let fish_entry = nation_output
            .get(&ResourceType::Fish)
            .expect("fish entry exists");
        assert_eq!(fish_entry.0, 1, "port counts as improvement for fish");
        assert_eq!(fish_entry.1, 2, "ports yield two fish");

        assert!(
            production.tiles.iter().any(|tile| {
                tile.owner == nation
                    && tile.resource_type == ResourceType::Fish
                    && tile.tile_pos == TilePos { x: 1, y: 1 }
                    && tile.output == 2
                    && tile.source == ConnectedTileSource::Port
            }),
            "port fish debug tile recorded"
        );
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Reflect)]
pub enum BuildingKind {
    // Production buildings
    TextileMill,          // 2×Cotton OR 2×Wool → 1×Fabric
    LumberMill,           // 2×Timber → 1×Lumber OR 1×Paper
    SteelMill,            // 1×Iron + 1×Coal → 1×Steel
    FoodProcessingCenter, // 2×Grain + 1×Fruit + 1×(Livestock|Fish) → 2×CannedFood
    ClothingFactory,      // 2×Fabric → 1×Clothing
    FurnitureFactory,     // 2×Lumber → 1×Furniture
    MetalWorks,           // 2×Steel → 1×Hardware OR 1×Armaments
    Refinery,             // 2×Oil → 1×Fuel
    Railyard,             // 1×Steel + 1×Lumber → 1×Transport
    Shipyard,             // 1×Steel + 1×Lumber + 1×Fuel → 1×Ship

    // Worker-related buildings (no production capacity)
    Capitol,     // Recruit untrained workers
    TradeSchool, // Train workers
    PowerPlant,  // Convert fuel to labor
}

/// What input material a building should use for production
#[derive(Debug, Clone, Copy, PartialEq, Eq, Reflect)]
pub enum ProductionChoice {
    // For TextileMill: choose between Cotton or Wool
    UseCotton,
    UseWool,

    // For LumberMill: choose between Lumber or Paper
    MakeLumber,
    MakePaper,

    // For FoodProcessingCenter: choose between Livestock or Fish
    UseLivestock,
    UseFish,

    // For MetalWorks: choose between Hardware or Armaments
    MakeHardware,
    MakeArmaments,
}

/// Production settings for a building (persists turn-to-turn)
#[derive(Component, Debug, Clone, Reflect)]
#[reflect(Component)]
pub struct ProductionSettings {
    /// What input material to use (e.g., Cotton vs Wool for textile mill)
    pub choice: ProductionChoice,
    /// How many units to produce this turn (capped by capacity and inputs)
    pub target_output: u32,
}

impl Default for ProductionSettings {
    fn default() -> Self {
        Self {
            choice: ProductionChoice::UseCotton,
            target_output: 0,
        }
    }
}

#[derive(Component, Debug, Clone, Copy, Reflect)]
#[reflect(Component)]
pub struct Building {
    pub kind: BuildingKind,
    pub capacity: u32, // Maximum output per turn
}

impl Building {
    pub fn textile_mill(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::TextileMill,
            capacity,
        }
    }

    pub fn lumber_mill(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::LumberMill,
            capacity,
        }
    }

    pub fn steel_mill(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::SteelMill,
            capacity,
        }
    }

    pub fn food_processing_center(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::FoodProcessingCenter,
            capacity,
        }
    }

    pub fn clothing_factory(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::ClothingFactory,
            capacity,
        }
    }

    pub fn furniture_factory(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::FurnitureFactory,
            capacity,
        }
    }

    pub fn metal_works(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::MetalWorks,
            capacity,
        }
    }

    pub fn refinery(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::Refinery,
            capacity,
        }
    }

    pub fn railyard() -> Self {
        Self {
            kind: BuildingKind::Railyard,
            capacity: u32::MAX, // Unlimited capacity - limited only by inputs and labor
        }
    }

    pub fn shipyard() -> Self {
        Self {
            kind: BuildingKind::Shipyard,
            capacity: u32::MAX,
        }
    }

    pub fn capitol() -> Self {
        Self {
            kind: BuildingKind::Capitol,
            capacity: 0, // Not a production building
        }
    }

    pub fn trade_school() -> Self {
        Self {
            kind: BuildingKind::TradeSchool,
            capacity: 0, // Not a production building
        }
    }

    pub fn power_plant(capacity: u32) -> Self {
        Self {
            kind: BuildingKind::PowerPlant,
            capacity, // Fuel → labor conversion capacity
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Ingredient {
    pub good: Good,
    pub amount: u32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ProductAmount {
    pub good: Good,
    pub amount: u32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RecipeVariant {
    inputs: &'static [Ingredient],
    outputs: &'static [ProductAmount],
}

impl RecipeVariant {
    pub fn inputs(&self) -> &'static [Ingredient] {
        self.inputs
    }

    pub fn outputs(&self) -> &'static [ProductAmount] {
        self.outputs
    }

    pub fn primary_output(&self) -> Option<ProductAmount> {
        self.outputs.first().copied()
    }

    pub fn primary_output_good(&self) -> Option<Good> {
        self.primary_output().map(|output| output.good)
    }

    pub fn primary_output_amount(&self) -> u32 {
        self.primary_output()
            .map(|output| output.amount)
            .unwrap_or(0)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RecipeVariantInfo {
    pub choice: Option<ProductionChoice>,
    pub variant: RecipeVariant,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ProductionRecipe {
    variants: &'static [RecipeVariantDefinition],
}

impl ProductionRecipe {
    pub fn variant_for_choice(&self, choice: ProductionChoice) -> Option<RecipeVariant> {
        self.variants
            .iter()
            .find(|definition| definition.choice == Some(choice))
            .or_else(|| {
                self.variants
                    .iter()
                    .find(|definition| definition.choice.is_none())
            })
            .map(|definition| definition.variant)
    }

    pub fn variants_for_output(&self, output_good: Good) -> Vec<RecipeVariantInfo> {
        self.variants_iter(output_good).collect()
    }

    pub fn input_amount_for(&self, output_good: Good, input_good: Good) -> Option<u32> {
        self.variants_iter(output_good).find_map(|info| {
            info.variant
                .inputs
                .iter()
                .find(|ingredient| ingredient.good == input_good)
                .map(|ingredient| ingredient.amount)
        })
    }

    pub fn produces(&self, output_good: Good) -> bool {
        self.variants_iter(output_good).next().is_some()
    }

    fn variants_iter(&self, output_good: Good) -> impl Iterator<Item = RecipeVariantInfo> + '_ {
        self.variants
            .iter()
            .filter(move |definition| {
                definition
                    .variant
                    .primary_output_good()
                    .is_some_and(|good| good == output_good)
            })
            .map(|definition| RecipeVariantInfo {
                choice: definition.choice,
                variant: definition.variant,
            })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct RecipeVariantDefinition {
    choice: Option<ProductionChoice>,
    variant: RecipeVariant,
}

const TEXTILE_COTTON_INPUTS: [Ingredient; 1] = [Ingredient {
    good: Good::Cotton,
    amount: 2,
}];
const TEXTILE_WOOL_INPUTS: [Ingredient; 1] = [Ingredient {
    good: Good::Wool,
    amount: 2,
}];
const TEXTILE_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Fabric,
    amount: 1,
}];
const TEXTILE_VARIANTS: [RecipeVariantDefinition; 2] = [
    RecipeVariantDefinition {
        choice: Some(ProductionChoice::UseCotton),
        variant: RecipeVariant {
            inputs: &TEXTILE_COTTON_INPUTS,
            outputs: &TEXTILE_OUTPUTS,
        },
    },
    RecipeVariantDefinition {
        choice: Some(ProductionChoice::UseWool),
        variant: RecipeVariant {
            inputs: &TEXTILE_WOOL_INPUTS,
            outputs: &TEXTILE_OUTPUTS,
        },
    },
];
const TEXTILE_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &TEXTILE_VARIANTS,
};

const LUMBER_INPUTS: [Ingredient; 1] = [Ingredient {
    good: Good::Timber,
    amount: 2,
}];
const LUMBER_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Lumber,
    amount: 1,
}];
const PAPER_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Paper,
    amount: 1,
}];
const LUMBER_VARIANTS: [RecipeVariantDefinition; 2] = [
    RecipeVariantDefinition {
        choice: Some(ProductionChoice::MakeLumber),
        variant: RecipeVariant {
            inputs: &LUMBER_INPUTS,
            outputs: &LUMBER_OUTPUTS,
        },
    },
    RecipeVariantDefinition {
        choice: Some(ProductionChoice::MakePaper),
        variant: RecipeVariant {
            inputs: &LUMBER_INPUTS,
            outputs: &PAPER_OUTPUTS,
        },
    },
];
const LUMBER_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &LUMBER_VARIANTS,
};

const STEEL_INPUTS: [Ingredient; 2] = [
    Ingredient {
        good: Good::Iron,
        amount: 1,
    },
    Ingredient {
        good: Good::Coal,
        amount: 1,
    },
];
const STEEL_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Steel,
    amount: 1,
}];
const STEEL_VARIANTS: [RecipeVariantDefinition; 1] = [RecipeVariantDefinition {
    choice: None,
    variant: RecipeVariant {
        inputs: &STEEL_INPUTS,
        outputs: &STEEL_OUTPUTS,
    },
}];
const STEEL_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &STEEL_VARIANTS,
};

const FOOD_LIVESTOCK_INPUTS: [Ingredient; 3] = [
    Ingredient {
        good: Good::Grain,
        amount: 2,
    },
    Ingredient {
        good: Good::Fruit,
        amount: 1,
    },
    Ingredient {
        good: Good::Livestock,
        amount: 1,
    },
];
const FOOD_FISH_INPUTS: [Ingredient; 3] = [
    Ingredient {
        good: Good::Grain,
        amount: 2,
    },
    Ingredient {
        good: Good::Fruit,
        amount: 1,
    },
    Ingredient {
        good: Good::Fish,
        amount: 1,
    },
];
const FOOD_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::CannedFood,
    amount: 2,
}];
const FOOD_VARIANTS: [RecipeVariantDefinition; 2] = [
    RecipeVariantDefinition {
        choice: Some(ProductionChoice::UseLivestock),
        variant: RecipeVariant {
            inputs: &FOOD_LIVESTOCK_INPUTS,
            outputs: &FOOD_OUTPUTS,
        },
    },
    RecipeVariantDefinition {
        choice: Some(ProductionChoice::UseFish),
        variant: RecipeVariant {
            inputs: &FOOD_FISH_INPUTS,
            outputs: &FOOD_OUTPUTS,
        },
    },
];
const FOOD_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &FOOD_VARIANTS,
};

const CLOTHING_INPUTS: [Ingredient; 1] = [Ingredient {
    good: Good::Fabric,
    amount: 2,
}];
const CLOTHING_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Clothing,
    amount: 1,
}];
const CLOTHING_VARIANTS: [RecipeVariantDefinition; 1] = [RecipeVariantDefinition {
    choice: None,
    variant: RecipeVariant {
        inputs: &CLOTHING_INPUTS,
        outputs: &CLOTHING_OUTPUTS,
    },
}];
const CLOTHING_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &CLOTHING_VARIANTS,
};

const FURNITURE_INPUTS: [Ingredient; 1] = [Ingredient {
    good: Good::Lumber,
    amount: 2,
}];
const FURNITURE_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Furniture,
    amount: 1,
}];
const FURNITURE_VARIANTS: [RecipeVariantDefinition; 1] = [RecipeVariantDefinition {
    choice: None,
    variant: RecipeVariant {
        inputs: &FURNITURE_INPUTS,
        outputs: &FURNITURE_OUTPUTS,
    },
}];
const FURNITURE_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &FURNITURE_VARIANTS,
};

const METAL_INPUTS: [Ingredient; 1] = [Ingredient {
    good: Good::Steel,
    amount: 2,
}];
const HARDWARE_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Hardware,
    amount: 1,
}];
const ARMAMENT_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Armaments,
    amount: 1,
}];
const METAL_VARIANTS: [RecipeVariantDefinition; 2] = [
    RecipeVariantDefinition {
        choice: Some(ProductionChoice::MakeHardware),
        variant: RecipeVariant {
            inputs: &METAL_INPUTS,
            outputs: &HARDWARE_OUTPUTS,
        },
    },
    RecipeVariantDefinition {
        choice: Some(ProductionChoice::MakeArmaments),
        variant: RecipeVariant {
            inputs: &METAL_INPUTS,
            outputs: &ARMAMENT_OUTPUTS,
        },
    },
];
const METAL_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &METAL_VARIANTS,
};

const REFINERY_INPUTS: [Ingredient; 1] = [Ingredient {
    good: Good::Oil,
    amount: 2,
}];
const REFINERY_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Fuel,
    amount: 1,
}];
const REFINERY_VARIANTS: [RecipeVariantDefinition; 1] = [RecipeVariantDefinition {
    choice: None,
    variant: RecipeVariant {
        inputs: &REFINERY_INPUTS,
        outputs: &REFINERY_OUTPUTS,
    },
}];
const REFINERY_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &REFINERY_VARIANTS,
};

const RAILYARD_INPUTS: [Ingredient; 2] = [
    Ingredient {
        good: Good::Steel,
        amount: 1,
    },
    Ingredient {
        good: Good::Lumber,
        amount: 1,
    },
];
const RAILYARD_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Transport,
    amount: 1,
}];
const RAILYARD_VARIANTS: [RecipeVariantDefinition; 1] = [RecipeVariantDefinition {
    choice: None,
    variant: RecipeVariant {
        inputs: &RAILYARD_INPUTS,
        outputs: &RAILYARD_OUTPUTS,
    },
}];
const RAILYARD_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &RAILYARD_VARIANTS,
};

const SHIPYARD_INPUTS: [Ingredient; 3] = [
    Ingredient {
        good: Good::Steel,
        amount: 1,
    },
    Ingredient {
        good: Good::Lumber,
        amount: 1,
    },
    Ingredient {
        good: Good::Fuel,
        amount: 1,
    },
];
const SHIPYARD_OUTPUTS: [ProductAmount; 1] = [ProductAmount {
    good: Good::Ship,
    amount: 1,
}];
const SHIPYARD_VARIANTS: [RecipeVariantDefinition; 1] = [RecipeVariantDefinition {
    choice: None,
    variant: RecipeVariant {
        inputs: &SHIPYARD_INPUTS,
        outputs: &SHIPYARD_OUTPUTS,
    },
}];
const SHIPYARD_RECIPE: ProductionRecipe = ProductionRecipe {
    variants: &SHIPYARD_VARIANTS,
};

const PRODUCTION_RECIPES: &[(BuildingKind, &ProductionRecipe)] = &[
    (BuildingKind::TextileMill, &TEXTILE_RECIPE),
    (BuildingKind::LumberMill, &LUMBER_RECIPE),
    (BuildingKind::SteelMill, &STEEL_RECIPE),
    (BuildingKind::FoodProcessingCenter, &FOOD_RECIPE),
    (BuildingKind::ClothingFactory, &CLOTHING_RECIPE),
    (BuildingKind::FurnitureFactory, &FURNITURE_RECIPE),
    (BuildingKind::MetalWorks, &METAL_RECIPE),
    (BuildingKind::Refinery, &REFINERY_RECIPE),
    (BuildingKind::Railyard, &RAILYARD_RECIPE),
    (BuildingKind::Shipyard, &SHIPYARD_RECIPE),
];

pub fn production_recipe(kind: BuildingKind) -> Option<&'static ProductionRecipe> {
    PRODUCTION_RECIPES
        .iter()
        .find_map(|(recipe_kind, recipe)| (*recipe_kind == kind).then_some(*recipe))
}

pub fn building_for_output(output_good: Good) -> Option<BuildingKind> {
    PRODUCTION_RECIPES
        .iter()
        .find_map(|(kind, recipe)| recipe.produces(output_good).then_some(*kind))
}

pub fn input_requirement_per_unit(
    kind: BuildingKind,
    output_good: Good,
    input_good: Good,
) -> Option<u32> {
    production_recipe(kind)?.input_amount_for(output_good, input_good)
}

/// Collection of all buildings for a nation
#[derive(Component, Debug, Clone, Default, Reflect)]
#[reflect(Component)]
pub struct Buildings {
    pub buildings: HashMap<BuildingKind, Building>,
}

impl Buildings {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_all_initial() -> Self {
        let mut buildings = HashMap::new();
        buildings.insert(BuildingKind::TextileMill, Building::textile_mill(8));
        buildings.insert(BuildingKind::LumberMill, Building::lumber_mill(4));
        buildings.insert(BuildingKind::SteelMill, Building::steel_mill(4));
        buildings.insert(
            BuildingKind::FoodProcessingCenter,
            Building::food_processing_center(4),
        );
        buildings.insert(BuildingKind::ClothingFactory, Building::clothing_factory(2));
        buildings.insert(
            BuildingKind::FurnitureFactory,
            Building::furniture_factory(2),
        );
        buildings.insert(BuildingKind::MetalWorks, Building::metal_works(2));
        buildings.insert(BuildingKind::Refinery, Building::refinery(2));
        buildings.insert(BuildingKind::Railyard, Building::railyard());
        buildings.insert(BuildingKind::Shipyard, Building::shipyard());
        Self { buildings }
    }

    pub fn get(&self, kind: BuildingKind) -> Option<Building> {
        self.buildings.get(&kind).copied()
    }

    pub fn insert(&mut self, building: Building) {
        self.buildings.insert(building.kind, building);
    }
}

/// Runs production across all entities that have both a Stockpile and a Building.
/// Consumes reserved resources and produces outputs.
/// Production rules follow 2:1 ratios (2 inputs → 1 output).
/// Production now requires labor points from workers.
///
/// Note: This system runs via OnEnter(TurnPhase::Processing) in ProcessingSet::Production,
/// so no phase check is needed.
pub fn run_production(
    mut q: Query<(
        Option<&Workforce>,
        &mut Stockpile,
        &Building,
        &mut ProductionSettings,
    )>,
) {
    for (workforce_opt, mut stock, building, mut settings) in q.iter_mut() {
        // Calculate available labor (0 if no workforce)
        let available_labor = workforce_opt.map(|w| w.available_labor()).unwrap_or(0);

        // Each unit of production requires 1 labor point
        // This acts as another constraint on production alongside capacity and inputs
        let max_from_labor = available_labor;
        let Some(recipe) = production_recipe(building.kind) else {
            continue;
        };

        let desired_output = settings
            .target_output
            .min(max_from_labor)
            .min(building.capacity);
        if desired_output == 0 {
            settings.target_output = 0;
            continue;
        }

        let Some(variant) = recipe.variant_for_choice(settings.choice) else {
            settings.target_output = 0;
            debug!(
                "Skipping production for {:?}: no variant for choice {:?}",
                building.kind, settings.choice
            );
            continue;
        };

        let output_per_batch = variant.primary_output_amount();
        if output_per_batch == 0 {
            settings.target_output = 0;
            continue;
        }

        let target_batches = desired_output.div_ceil(output_per_batch);
        if target_batches == 0 {
            settings.target_output = 0;
            continue;
        }

        let (produced_output, consumption) = execute_variant(&mut stock, variant, target_batches);

        if produced_output < desired_output {
            log_production_shortfall(
                building.kind,
                variant,
                desired_output,
                produced_output,
                &consumption,
            );
        }

        settings.target_output = produced_output;
    }
}

#[derive(Clone, Debug)]
struct ConsumptionRecord {
    ingredient: Ingredient,
    consumed: u32,
    required: u32,
}

fn execute_variant(
    stock: &mut Stockpile,
    variant: RecipeVariant,
    target_batches: u32,
) -> (u32, Vec<ConsumptionRecord>) {
    if target_batches == 0 {
        return (0, Vec::new());
    }

    let mut actual_batches = target_batches;
    let mut consumption = Vec::with_capacity(variant.inputs().len());

    for ingredient in variant.inputs() {
        let required = ingredient.amount.saturating_mul(target_batches);
        let consumed = if required > 0 {
            stock.consume_reserved(ingredient.good, required)
        } else {
            0
        };
        if ingredient.amount > 0 {
            actual_batches = actual_batches.min(consumed / ingredient.amount);
        }
        consumption.push(ConsumptionRecord {
            ingredient: *ingredient,
            consumed,
            required,
        });
    }

    let primary_output = variant.primary_output();
    let mut produced_primary = 0;

    for output in variant.outputs() {
        let produced_amount = actual_batches.saturating_mul(output.amount);
        if produced_amount > 0 {
            stock.add(output.good, produced_amount);
        }
        if primary_output.is_some_and(|primary| primary.good == output.good) {
            produced_primary = produced_amount;
        }
    }

    (produced_primary, consumption)
}

fn log_production_shortfall(
    building_kind: BuildingKind,
    variant: RecipeVariant,
    requested_output: u32,
    produced_output: u32,
    consumption: &[ConsumptionRecord],
) {
    if produced_output >= requested_output {
        return;
    }

    let Some(output_good) = variant.primary_output_good() else {
        warn!(
            "{:?}: requested {} output but recipe variant has no primary output good (produced {}). Consumption: {:?}",
            building_kind, requested_output, produced_output, consumption
        );
        return;
    };

    let details = if consumption.is_empty() {
        "no inputs consumed".to_string()
    } else {
        consumption
            .iter()
            .map(|record| {
                format!(
                    "{:?} {}/{}",
                    record.ingredient.good, record.consumed, record.required
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    info!(
        "{:?}: requested {} {:?} but produced {} ({})",
        building_kind, requested_output, output_good, produced_output, details
    );
}
